version: "3.9"

networks: 
  fp-fetcher:
    external: true

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DB_URL: db
    depends_on:
      - db
    networks: 
      - fp-fetcher
  
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    networks: 
      - fp-fetcher

volumes:
  mongo-data: